services:
  whatsapp:
    build: .
    container_name: whatsapp
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - WEBSOCKET_URL=ws://tcc-rails-app-1:3000/cable?token=this_should_never_be_in_prod
    volumes:
      - ./session.json:/usr/src/app/session.json
    # depends_on:
    #   - stream
    networks:
      - tcc_app_network
    ports:
      - "3333:3333" # this isn't needed, make it anything th
networks:
  tcc_app_network:
    driver: bridge
    external: true # join the existing one because you're already running the main app in a different compose file
