services:
  whatsapp:
    build: .
    container_name: whatsapp-web-app
    restart: always
    environment:
      - NODE_ENV=development
      - KAFKA_URL=stream:9092
    volumes:
      - ./session.json:/usr/src/app/session.json
    depends_on:
      - stream
    networks:
      - default
    ports:
      - "3000:3000"
  stream:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://stream:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://stream:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr stream:33145
      - --advertise-rpc-addr stream:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.5
    container_name: stream
    volumes:
      - stream-data:/var/lib/redpanda/data
    networks:
    - default
    ports:
      - 18081:18081
      - 18082:18082
      - 9092:9092
      - 19092:19092
      - 19644:9644

networks:
  app-network:
    driver: bridge

volumes:
  stream-data: