name: Build and Publish Docker Image to GitHub Container Registry

# Trigger the workflow on push to main
on:
  push:
    paths:
      - 'whatsapp-client/**'
    branches:
      - main

# Define environment variables
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/whatsapp-client
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (necessary for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build the Docker image and tag it
      - name: Build the Docker image
        run: |
          docker build . -t $IMAGE_NAME:$TAG

      # Step 5: Push the Docker image to GitHub Container Registry (GHCR)
      - name: Push the Docker image
        run: |
          docker push $IMAGE_NAME:$TAG

      # Step 6: Verify the Docker image digest (Optional)
      - name: Docker Image Digest
        run: |
          echo "Published image digest:"
          docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME:$TAG